#!/usr/bin/env bash

docker run --name phoenix-postman \
           --rm \
           -v "$PWD":/opt/app \
           -w /opt/app \
           -i \
           -p 4000:4000 \
           --env-file ./variables.env \
           -t elixir:1.6.0 \
           /bin/bash -c "mix local.hex --force; \
                         mix local.rebar --force; \
                         bash"
